[package]
name = "tests-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
borsh = "0.9"
near-units = "0.1.0"
serde = "1.0"
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
tokio = { version = "1.10.0", features = ["full"] }
workspaces = "0.3.1"
futures = "0.3.21"

[workspace]