name: Pull Request Checker
on: pull_request

jobs:
  check_build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup component add rustfmt
          rustup target add wasm32-unknown-unknown

      - name: Install Yarn Globally
        run: npm install -g yarn
      
      - name: Installing Dependencies
        run: yarn

      - name: Rust Tests
        run: yarn contract:cargo:tests

      - name: Lib Tests
        run: yarn contract:lib:tests
      
      - name: Web Build
        run: yarn web:build

