name: Pull Request Checker
on: pull_request

jobs:
  check_build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: raftario/setup-rust-action@v1

      - name: Get yarn cache
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Dependencies Installation
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: install --ignore-engines

      - name: Rust Setup
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

      - name: Contract Unit Rust Tests
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: contract:cargo:tests

      - name: Contract integration tests
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: contract:lib:tests

      - name: Contract Rust Build 
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: contract:build
  
      - name: Dapp Build
        uses: borales/actions-yarn/@v2.0.0
        with:
          cmd: web:build

